name: Auto-Update Courses and Certs

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering from the Actions tab

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # Use your PAT for checkout
      # ... rest of your workflow ...
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add courses.json
          git commit -m "Auto-update courses and certs data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use your PAT for push
