name: Auto-Update Courses and Certs

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch and update courses data
        run: |
          curl -s 'https://api.rss2json.com/v1/api.json?rss_url=https://www.coursera.org/browse/computer-science/free' | jq '.items | map({title: .title, link: .link + "?aff=your_aff_id"}) | .[0:5]' > courses.json

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add courses.json
          git commit -m "Auto-update courses and certs data" || echo "No changes to commit"
          git push
